server {
    listen ${PORT};
    client_max_body_size 50M;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass ${API_URL}/;
        proxy_set_header Host $host;
        proxy_read_timeout 120s;
    }
}